spring:
  application:
    name: car-wash-api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: user_service
            uri: http://localhost:8081
            predicates:
              - Path=/user/**

          - id: car_service
            uri: http://localhost:8082
            predicates:
              - Path=/car/**

          - id: booking_service
            uri: http://localhost:8083
            predicates:
              - Path=/booking/**

server:
  port: 8080

