spring:
  application:
    name: car-wash-api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: user_service
            uri: http://localhost:8081
            predicates:
              - Path=/user/**



server:
  port: 8080

